name: Scheduled Python Script

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the beginning of every hour

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add your dependencies here, e.g.,
        # pip install requests

    - name: Run script
      run: python your_script.py
